/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRequest {
  'serviceType' : ServiceType,
  'name' : string,
  'email' : string,
  'message' : string,
  'preferredDate' : bigint,
  'timestamp' : bigint,
  'phone' : string,
  'selectedPlan' : [] | [string],
}
export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type ServiceType = { 'cabinetPainting' : null } |
  { 'interiorPainting' : null } |
  { 'commercial' : null } |
  { 'exteriorPainting' : null };
export interface Subscription {
  'name' : string,
  'email' : string,
  'phone' : string,
  'planName' : string,
  'startDate' : bigint,
}
export interface SubscriptionPlan {
  'features' : Array<string>,
  'name' : string,
  'pricePerYear' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSubscriptionPlan' : ActorMethod<[SubscriptionPlan], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteSubscriptionPlan' : ActorMethod<[string], undefined>,
  'getAllBookingRequests' : ActorMethod<[], Array<BookingRequest>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlan>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBookingRequest' : ActorMethod<[BookingRequest], undefined>,
  'submitContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'submitSubscription' : ActorMethod<[Subscription], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];