/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubscriptionPlan = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'pricePerYear' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'cabinetPainting' : IDL.Null,
  'interiorPainting' : IDL.Null,
  'commercial' : IDL.Null,
  'exteriorPainting' : IDL.Null,
});
export const BookingRequest = IDL.Record({
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Int,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'selectedPlan' : IDL.Opt(IDL.Text),
});
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Subscription = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'planName' : IDL.Text,
  'startDate' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSubscriptionPlan' : IDL.Func([SubscriptionPlan], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSubscriptionPlan' : IDL.Func([IDL.Text], [], []),
  'getAllBookingRequests' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSubscriptionPlans' : IDL.Func([], [IDL.Vec(SubscriptionPlan)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBookingRequest' : IDL.Func([BookingRequest], [], []),
  'submitContactMessage' : IDL.Func([ContactMessage], [], []),
  'submitSubscription' : IDL.Func([Subscription], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubscriptionPlan = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'pricePerYear' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'cabinetPainting' : IDL.Null,
    'interiorPainting' : IDL.Null,
    'commercial' : IDL.Null,
    'exteriorPainting' : IDL.Null,
  });
  const BookingRequest = IDL.Record({
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Int,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'selectedPlan' : IDL.Opt(IDL.Text),
  });
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Subscription = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'planName' : IDL.Text,
    'startDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSubscriptionPlan' : IDL.Func([SubscriptionPlan], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSubscriptionPlan' : IDL.Func([IDL.Text], [], []),
    'getAllBookingRequests' : IDL.Func(
        [],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSubscriptionPlans' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionPlan)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBookingRequest' : IDL.Func([BookingRequest], [], []),
    'submitContactMessage' : IDL.Func([ContactMessage], [], []),
    'submitSubscription' : IDL.Func([Subscription], [], []),
  });
};

export const init = ({ IDL }) => { return []; };